version: '3.9'

services:
  db:
    image: mysql:8.0.31
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'Secret1'
      MYSQL_DATABASE: 'cadastro'
    ports:
      - '3306:3306'
    expose:
      - '3306'

volumes:
  mysql-data: